### ISSUE TITLE
PBDB repository rename

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/changelog#14]
Attention all @paleobiodb/owners, here are the following suggested renames of repos. Changing the repo names will make things easier to follow and understand. This WILL NOT break branches under the repos or files and directory names on local disks so no worries.

Old -> New
navigator -> Navigator
pbdb-main -> SplashPage
pbdb-new -> DataService
beta-testing-group -> BetaTesters
pbdb-wing -> WebApp
paleobiodb_utilities -> AnalysisTools
teachPaleobiology -> Suggest move to @aazaff personal repo
Wing -> This is a fork, leave as is
larkin -> Larkin or leave as is
pbdb_changelog -> ChangeLog
pbdb-classic -> Original-PBDB-Codebase
pdd -> Do we need this fork here, there have been no commits from our group to it. If yes please write a readme for it because we don't know what it is.

Comment on this issue by the end of the week, @jpjenk will make these changes Friday afternoon.

**Comment by aazaff** [comment]
A few comments

1) We do not need the pdd repo as part of the paleobiodb organization anymore.
2) @jczaplew would like all repo names to be lower snake_case or camelCase instead of PascalCase
3) The teachPaleobiology repo was originally in my personal account, but was moved here at @cambro's suggestion because it was paid for by a grant specifically to PBDB to develop this. I am open to moving it back, however, if desired.
4) Yes, the repo name change could theoretically break paths under rare circumstances if you are not using "relative paths". However, we should **always** be using relative paths.
5) Just call it classic, Original-PBDB-Codebase is too verbose and unclear. We still call it classic in the actual documentation of things.

**Comment by jpjenk** [comment]
1) The pdd repo fork has been removed.
2) We will use snake_case for all the new repo names. It's more Pythonic anyway so you won't get any complaints from me.
3) I don't have a strong opinion on teachPaleobiology other than it doesn't fit our new naming convention; "course_materials" perhaps. However, as the objective here is to clean up the group account and nobody else is likely to contribute to this, perhaps it does belong to @aazaff's account.
4) Yes, don't use absolute paths. I have cloned most of our important repos into directories then changed the names of them to something I prefer anyway and have not had issues so I think we are okay here.
5) Would like to retire the name "classic" since a lot of the old, so called, classic code is embedded in the new WebApp framework (note: it runs differently though as it is no longer a monolithic CGI app). I like "historical_codebase" or "legacy_codebase" as it is no longer maintained and exists as a backup/reference only (note: it is a private repo)

**Comment by aazaff** [comment]
teachPaleobiology has been transferred back.

**Comment by jpjenk** [comment]
Attention @paleobiodb/owners, @vjpsyverson and @markuhen. Repository names have been changed and some of the descriptions updated.

**Comment by jpjenk** [comment]
Also a repo simply named "utilities" has been created to house system administration, data integrity/cleanup and other custom scripts (such as the forthcoming GBIF export tool). This is not a location for maintenance and bootstrap scripts integral to the operation of the PBDB backend, they live in the data_service repo. It is also not to be confused with the previous repo for scientific analysis code which is now renamed analysis_tools.
